// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARWlfwRcy3gQYwBwnRruzn52P8QFNeW2c',
    appId: '1:221055607585:android:72cc8ca28c3b87ee91d460',
    messagingSenderId: '221055607585',
    projectId: 'kargala-65983',
    storageBucket: 'kargala-65983.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUK0xaXCHUWdZBjOqTLAOfBmkVqv5Sh8',
    appId: '1:221055607585:web:74daa3b77787554991d460',
    messagingSenderId: '221055607585',
    projectId: 'kargala-65983',
    authDomain: 'kargala-65983.firebaseapp.com',
    storageBucket: 'kargala-65983.firebasestorage.app',
    measurementId: 'G-79W9DHRLLB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfyyhmfs4OrZ5U8F9OMaSMNSwC1loXHvI',
    appId: '1:221055607585:ios:5624cb8f94a08d4891d460',
    messagingSenderId: '221055607585',
    projectId: 'kargala-65983',
    storageBucket: 'kargala-65983.firebasestorage.app',
    androidClientId: '221055607585-i7qcq603r6u0enmm3ra1gjnm4g95o3j6.apps.googleusercontent.com',
    iosClientId: '221055607585-uvr5jot334536d4pgc12gl3ius72atqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kargala',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfyyhmfs4OrZ5U8F9OMaSMNSwC1loXHvI',
    appId: '1:221055607585:ios:5624cb8f94a08d4891d460',
    messagingSenderId: '221055607585',
    projectId: 'kargala-65983',
    storageBucket: 'kargala-65983.firebasestorage.app',
    androidClientId: '221055607585-i7qcq603r6u0enmm3ra1gjnm4g95o3j6.apps.googleusercontent.com',
    iosClientId: '221055607585-uvr5jot334536d4pgc12gl3ius72atqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kargala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjUK0xaXCHUWdZBjOqTLAOfBmkVqv5Sh8',
    appId: '1:221055607585:web:cffa6406a0f2c52b91d460',
    messagingSenderId: '221055607585',
    projectId: 'kargala-65983',
    authDomain: 'kargala-65983.firebaseapp.com',
    storageBucket: 'kargala-65983.firebasestorage.app',
    measurementId: 'G-6G89RQ6R4S',
  );

}